#!/usr/bin/env bash

# this is a simple config for herbstluftwm

# variables
# Tokyo Night theme colors
color_bg="#1a1b26"
color_bg_light="#24283b"
color_fg="#ffffff"
color_fg_dim="#565f89"
color_blue="#6dade3"
color_sandy="#e3a36d"
color_cyan="#0db9d7"
color_green="#9ece6a"
color_teal="#63b7b7"
color_magenta="#9a6ace"
color_red="#d72b0d" #"0db9d7"
color_lavendar="#ad8ee6"
color_mint="#c7e68e"
color_black="#15161e"


hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-q close
#hc keybind $Mod-shift-q pkill herbstlaubwm
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Return spawn "${TERMINAL:-alacritty}" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-d spawn rofi -show drun

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# Set standard layout to grid
hc set default_frame_layout grid

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Set tag 1 to grid. (Root-frame exsits before default_frame_layout)
hc load "${tag_names[0]}" '(clients grid:0)'

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-a floating toggle
hc keybind $Mod-f set_layout max
hc keybind $Mod-g set_layout grid
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 grid vertical max horizontal    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# multimedia actions, volume and LCD brightness

hc keybind "XF86AudioPlay"  spawn playerctl play-pause
hc keybind "XF86AudioPause" spawn playerctl play-pause
hc keybind "XF86AudioNext"  spawn playerctl next
hc keybind "XF86AudioPrev"  spawn playerctl previous
hc keybind "XF86AudioStop"  spawn playerctl stop

hc keybind "XF86AudioRaiseVolume" spawn sh -c 'wpctl set-volume --limit 1.0 @DEFAULT_AUDIO_SINK@ 5%+; herbstclient emit_hook volume_refresh'
hc keybind "XF86AudioLowerVolume" spawn sh -c 'wpctl set-volume --limit 1.0 @DEFAULT_AUDIO_SINK@ 5%-; herbstclient emit_hook volume_refresh'
hc keybind "XF86AudioMute"        spawn sh -c 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle; herbstclient emit_hook volume_refresh'
hc keybind "XF86AudioMicMute"     spawn wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

hc keybind "XF86MonBrightnessUp"  spawn sh -c 'brightnessctl -e4 -n2 set 5%+; herbstclient emit_hook brightness_refresh'
hc keybind "XF86MonBrightnessDown"    spawn sh -c 'brightnessctl -e4 -n2 set 5%-; herbstclient emit_hook brightness_refresh'

hc keybind $Mod-s spawn sh -c 'maim -s | xclip -selection clipboard -t image/png'

# hc theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color "${color_cyan}cc"
hc set frame_border_normal_color "${color_bg}cc"
hc set frame_bg_normal_color "${color_bg_light}aa"
hc set frame_bg_active_color "${color_cyan}aa"
hc set frame_border_width 1
hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 4

hc attr theme.title_height 20
hc attr theme.title_when always
hc attr theme.title_font '-adobe-helvetica-medium-r-normal--14-100-100-100-p-76-iso8859-1'
hc attr theme.title_depth 3
hc attr theme.active.color "${color_bg_light}ef"
hc attr theme.title_color "$color_fg"
hc attr theme.normal.color "${color_bg_light}dd"
hc attr theme.urgent.color "${color_fg}dd"
hc attr theme.tab_color "${color_bg}dd"
hc attr theme.active.tab_color "${color_bg_light}dd"
hc attr theme.active.tab_outer_color "${color_fg}dd"
hc attr theme.active.tab_title_color "$color_fg"
hc attr theme.normal.title_color "$color_fg_dim"
hc attr theme.inner_width 3
hc attr theme.inner_color "$color_black"
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color "$color_black"
hc attr theme.active.inner_color "$color_magenta"
hc attr theme.urgent.inner_color "$color_red"
hc attr theme.normal.inner_color "$color_fg_dim"
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color "$color_bg"

hc set window_gap 5
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# Set monitor layout before hc will auto-detect monitors. The systemd service of autorandr will only trigger after sleep and on plugging.
autorandr --change
hc detect_monitors

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:


# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done

# set wallpaper
feh --bg-scale /home/thomas/Bilder/walls/landscapes/vally.jpg
